module.exports = function( _kreation, _anzAdj, _duzen, callback) {
    (function beleidigen() {
        wort = new
        Array("KackfassN", "SchmockenteufelM", "SchlafwagenschaffnerM", "LuftpumpeW", "HebammenkofferM", "WäscheleineW", "FrühstückN", "MilchbrötchenN", "HeckenschereW", "PappnaseW", "KabelklemmeW", "HammerwerferM", "WindbeutelM", "KlappstuhlM", "FäkalgesichtN", "BettnässerM", "MaraggeldaggelM", "FlitzpupeW", "HaubentaucherM", "AbziehbildN", "SumpfschnepfeW", "SchweinepriesterM", "SchnieptröteW", "rasende WildsauW", "LutscheiN", "HackfresseW", "HungerlatteW", "FeierabendpolitikerM", "WeihnachtsblödmannM", "GeschnackN", "SpaßbremseW", "ScheinasylantM", "SaftschlepperM", "NotleuchteW", "KuhmagenM", "WasserträgerM", "ZeckeW", "SchmierwurstW", "SeifenspenderM", "TrauerweideW", "HeulbojeW", "FlötenkönigM", "JammersackM", "ErsatzteilN", "FeierabendclownM", "PissbackeW", "FriedhofsjodlerM", "WeicheiN", "PausenclownM", "MuffensackM", "SchießbudenfigurW", "WarmduscherM", "SchurkeM", "AbschenkerM", "KlappspatenM", "TurnbeutelM", "HurensohnM", "QuastenflosserM", "EiterbeuleW", "FliegenfurzM", "Pillemann-SackfresseW", "PrimatM", "SchwachstrullerM", "ScheisshausdeckelM", "EinzellerM", "BremserM", "QuerulantM", "SpastiM", "StricherM", "BratarschM", "MasturbantM", "Neuzeit-JesusM", "MastdarmakrobatM", "GeizknochenM", "LeberwurstbrotN", "WuchtbrummeW", "BlödmannsgehilfeM", "HasenhirnN", "NasenbärM", "KackfroschM", "LöffelhirschM", "GesichtspilzM", "EiermalerM", "GipskopfM", "PlatzbuttergesichtN");
        beiwort = new Array("blöd", "stinkig", "ranzig", "faul", "modernd", "oxidierend", "rumhurend", "sabbernd", "abhängig", "wanzig", "rattig", "schleimig", "armselig", "neureich", "sitzengeblieben", "schimmelnd", "stinkend", "onanierend", "klebrig", "ölig", "kotzend", "schnodderig", "schlabberig", "ausgelutscht", "kaputt", "verbraucht", "mies");
        teil1 = new Array("Sack", "Kack", "Geiz", "Wucht", "Eier", "Gips", "Darm", "Piss", "Friedhofs", "Brat", "Schwach", "Hasen", "Turn", "Trauer", "Hunger", "Schein", "Weich", "Eiter", "Not", "Wild", "Lutsch", "Klapp", "Heul", "Warm", "Ersatz", "Arsch", "Falsch", "Gurken", "Müll", "Blöd", "Schorf", "Furz", "Hirn", "Brüll", "Schwabbel", "Anal", "Schwanz", "Kotz", "Knall", "Scham", "Mutti", "Scheiß", "Scheiß", "Dumpf", "Piß", "Dünn", "Schmalspur", "Dumm", "Bück", "Halb", "Höllen", "Kot", "Urin", "Napf", "Rüben", "Hilfs", "Sonderschul", "Toiletten", "Fehl", "Klo", "Dorf", "Bio", "Öko", "Blind", "Saft", "Knet", "Spacken", "Strich", "Genital", "Piss", "Suppen", "Knabber", "Öl", "Nebel", "Milch", "Quoten", "Wettkampf", "Beulen", "Rentner", "Pausen", "Weich", "Schmalz", "Schatten", "Kack", "Wald", "Fäkal", "Nudel", "Hunger");
        teil2 = new Array("hirnN", "bärM", "knochenM", "hirschM", "froschM", "malerM", "pilzM", "schnepfeW", "tussiW", "schlampeW", "beuleW", "clownM", "spatenM", "bremserM", "furzM", "backeW", "fresseW", "gehilfeM", "akrobatM", "figurW", "teufelM", "werferM", "klemmeW", "schälerM", "imitatN", "imitatN", "spatenM", "kopfM", "schülerM", "amputierterM", "schädelM", "hirnN", "lampeW", "proletM", "lappenM", "panzerM", "intruderM", "fresseW", "verschnittM", "düseW", "lutscherM", "biegerM", "eintopfM", "haufenM", "akrobatM", "ramboM", "tröteW", "pisserM", "geburtW", "trottelM", "bauerM", "wachtelW", "klumpenM", "eimerM", "geigerM", "hornN", "männchenN", "augeN", "warzeW", "softiM", "statistM", "schnitteW", "schänderM", "kackerM", "trägerM", "halterM", "putzerM", "stinkerM", "zählerM", "kifferM", "nascherM", "brotN", "arschM", "epileptikerM", "gräberM", "hüpferM", "dienerM", "sklaveM", "piratM", "bürsteW", "puperM", "erotikerM", "erotikerM", "schweinN", "kuhW", "tüteW", "treiberM", "vergesserM", "beuleW", "säuferM");
        var anzahlWort = 85;
        var anzahlBeiwort = 27;
        var anzahlTeil1 = 88;
        var anzahlTeil2 = 89;
        var x = 0;
        var t1 = 0;
        var y = 0;
        var t2 = 0;
        var test = "(C) 1999 Kami's Schimpfecke Markus Reynartz";
        var teiltest = "unautorisierte Verwendung VERBOTEN!";
        var geschlecht = "X";
        var help = "X";
        var basiswort = "HAH!";
        var duzen = "hehe";
        x = Math.floor(Math.random() * anzahlWort);
        y = Math.floor(Math.random() * anzahlBeiwort);
        t1 = Math.floor(Math.random() * anzahlTeil1);
        t2 = Math.floor(Math.random() * anzahlTeil2);
        teiltest = teil1[t1] + teil2[t2];
        basiswort = wort[x];
        if (_kreation) basiswort = teiltest;
        geschlecht = basiswort.charAt(basiswort.length - 1);
        if (geschlecht == "M") help = "er";
        if (geschlecht == "W") help = "e";
        if (geschlecht == "N") help = "es";
        anzahlAdj = _anzAdj + 1;
        beiwoerter = beiwort[y] + help;
        y = Math.floor(Math.random() * anzahlBeiwort);
        if (anzahlAdj >= 2) beiwoerter = beiwoerter + ", " + beiwort[y] + help;
        y = Math.floor(Math.random() * anzahlBeiwort);
        if (anzahlAdj == 3) beiwoerter = beiwoerter + ", " + beiwort[y] + help;
        test = beiwoerter + " " + basiswort.substr(0, basiswort.length - 1);
        if (_duzen) duzen = "Du";
        if (!_duzen) duzen = "Sie";
        callback(duzen + " " + test + " !!");
    })();
};
